services:
  web:
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile
    ports:
      - "3080:80"
    volumes:
      - ./:/var/www/symfony
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
    networks:
      - php-network

  php:
    image: php:8.4-fpm
    volumes:
      - ./:/var/www/symfony
    depends_on:
      - db
    networks:
      - php-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfonypassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - php-network

volumes:
  db_data:

networks:
  php-network:
    name: php-network
    external: true
