services:
  web:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "3080:80"
    volumes:
      - ./:/var/www/symfony
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.stock-symfony.rule=Host(`stock.nolandartois.fr`)
      - traefik.http.routers.stock-symfony.entrypoints=web
      - traefik.http.services.stock-symfony.loadbalancer.server.port=3080

  php:
    image: php:8.4-fpm
    volumes:
      - ./:/var/www/symfony
    depends_on:
      - db
    networks:
      - dokploy-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfonypassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - dokploy-network

volumes:
  db_data:

networks:
  dokploy-network:
    external: true
