services:

  web_server:
    image: nginx:1.27.4-alpine-slim
    restart: always
    volumes:
      - ./:/var/www
    ports:
      - 80:80
      - 443:443
    networks:
      - deployment-network

networks:
  deployment-network:
    driver: bridge
